# Just a binary for now, might make a library with tests
cxx_binary(
    name = 'disjoint_sets',
    header_namespace = '',
    srcs = [
        'disjoint_sets.cpp',
    ],
    compiler_flags = [
        '-Wall',
        '-Werror',
        '-Wextra',
        '-std=c++11',
    ],
)

# vim: set expandtab:ts=4:sw=4:smartindent
