CXX=g++
CXXFLAGS=-std=c++14 -O3 -Wall -Werror -Wextra

LIBS=

all: constructors

constructors: constructors.cpp
	$(CXX) $(CXXFLAGS) $(LIBS) constructors.cpp -o constructors

clean:
	rm -f constructors *.o
