cxx_library(
    name = 'variadic_lib',
    header_namespace = 'variadic',
    exported_headers = [
        'pack.h',
    ],
    compiler_flags = [
        '-Wall',
        '-Werror',
        '-Wextra',
        '-std=c++17',
    ],
)

cxx_test(
    name = 'variadic_test',
    srcs = [
        'test/pack_test.cpp',
    ],
    compiler_flags = [
        '-std=c++17',
        '-g',
        '-O0',
    ],
    deps = [
        ':variadic_lib',
    ],
)
